-- Amortizable liabilities: a liability can be marked amortizable, in which case its balance is
-- computed by a schedule (parts + rate revisions + prepayments) rather than a manual balance series.
-- A part starts either "from current balance" (project forward) or "from loan origin" (full schedule
-- incl. past); origin parts may re-anchor to a real balance at a date. The monthly job persists the
-- generated instalments. Enum-like columns (method, prepayment mode, start mode) are validated in the
-- service layer, not by CHECK constraints.

ALTER TABLE liabilities ADD COLUMN amortizable BOOLEAN NOT NULL DEFAULT FALSE;
-- Day of month the instalment is charged (1-31; a value past the month length clamps to its last day).
ALTER TABLE liabilities ADD COLUMN charge_day INTEGER;

CREATE TABLE amortization_parts (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    liability_id          UUID NOT NULL REFERENCES liabilities(id) ON DELETE CASCADE,
    label                 VARCHAR(120),
    method                VARCHAR(24) NOT NULL DEFAULT 'french',
    -- Outstanding balance at the starting point (current state); the schedule projects forward.
    original_principal    NUMERIC(15,2) NOT NULL,
    annual_rate           NUMERIC(8,4) NOT NULL DEFAULT 0,
    term_months           INTEGER,
    -- Optional: for French, an instalment supplied instead of a term (the other is derived).
    instalment            NUMERIC(15,2),
    start_date            DATE NOT NULL,
    -- 'current_balance' (project forward) or 'origin' (generate the full schedule incl. past).
    start_mode            VARCHAR(24) NOT NULL DEFAULT 'current_balance',
    -- Re-anchor (origin mode): the real outstanding balance at a date the schedule reprojects from.
    anchor_date           DATE,
    anchor_balance        NUMERIC(15,2),
    created_by_user_id    UUID NOT NULL REFERENCES users(id),
    updated_by_user_id    UUID NOT NULL REFERENCES users(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ
);
CREATE INDEX idx_amort_parts_liability ON amortization_parts(liability_id) WHERE deleted_at IS NULL;

CREATE TABLE amortization_rate_revisions (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id               UUID NOT NULL REFERENCES amortization_parts(id) ON DELETE CASCADE,
    effective_date        DATE NOT NULL,
    annual_rate           NUMERIC(8,4) NOT NULL,
    created_by_user_id    UUID NOT NULL REFERENCES users(id),
    updated_by_user_id    UUID NOT NULL REFERENCES users(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ
);
CREATE INDEX idx_amort_revisions_part ON amortization_rate_revisions(part_id, effective_date) WHERE deleted_at IS NULL;

CREATE TABLE amortization_prepayments (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id               UUID NOT NULL REFERENCES amortization_parts(id) ON DELETE CASCADE,
    prepayment_date       DATE NOT NULL,
    amount                NUMERIC(15,2) NOT NULL,
    -- 'reduce_term' (same instalment, finishes earlier) or 'reduce_instalment' (same term, lower instalment).
    mode                  VARCHAR(24) NOT NULL DEFAULT 'reduce_term',
    created_by_user_id    UUID NOT NULL REFERENCES users(id),
    updated_by_user_id    UUID NOT NULL REFERENCES users(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at            TIMESTAMPTZ
);
CREATE INDEX idx_amort_prepayments_part ON amortization_prepayments(part_id, prepayment_date) WHERE deleted_at IS NULL;

-- Automatic entries generated by the monthly job (one charged instalment): the exact history,
-- exported alongside the inputs for a faithful round-trip.
CREATE TABLE amortization_entries (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    part_id               UUID NOT NULL REFERENCES amortization_parts(id) ON DELETE CASCADE,
    charge_date           DATE NOT NULL,
    interest              NUMERIC(15,2) NOT NULL,
    principal             NUMERIC(15,2) NOT NULL,
    resulting_balance     NUMERIC(15,2) NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX idx_amort_entries_part_date ON amortization_entries(part_id, charge_date);
